version: '2'

volumes:
    logs:
        driver: local

services:
    php:
        build: .
        working_dir: /var/www
        tty: true
        volumes:
            - .:/var/www
            - logs:/var/www/logs
