name: Build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  testing:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 5.6
          - 7.0
          - 7.1
          - 7.2
          - 7.3
          - 7.4
          - 8.0
          - 8.1
          - 8.2
          - 8.3
        include:
          - phpunit: phpunit.xml
          - php: 5.6
            phpunit: phpunit.legacy.xml
          - php: 7.0
            phpunit: phpunit.legacy.xml
          - php: 7.1
            phpunit: phpunit.legacy.xml
          - php: 7.2
            phpunit: phpunit.legacy.xml
          - php: 7.3
            phpunit: phpunit.legacy.xml
          - php: 7.4
            phpunit: phpunit.legacy.xml
          - php: 8.0
            phpunit: phpunit.legacy.xml

    steps:
      - uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: date.timezone='UTC'
          extensions: xmlwriter
          tools: composer:v2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: php${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: php${{ matrix.php }}-composer-

      - name: Install dependencies
        run: composer install --no-plugins

      - name: Run test suite
        run: XDEBUG_MODE=coverage ./vendor/bin/phpunit --configuration ${{ matrix.phpunit }}

      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=build/logs/clover.xml -v
